-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-05-09 03:39:33.31

USE DER4

GO

-- tables
-- Table: AREAS
CREATE TABLE AREAS (
    IdArea int  NOT NULL IDENTITY,
    CONSTRAINT AREAS_pk PRIMARY KEY  (IdArea)
);

-- Table: CARRETERAS
CREATE TABLE CARRETERAS (
    IdCarretera int  NOT NULL IDENTITY,
    CONSTRAINT IdCarretera PRIMARY KEY  (IdCarretera)
);

-- Table: KILOMETROS
CREATE TABLE KILOMETROS (
    TRAMOS_IdTramo int  NOT NULL,
    MUNICIPIOS_IdMunicipio int  NOT NULL,
    KilometroEntrada int  NOT NULL,
    KilometroSalida int  NOT NULL,
    CONSTRAINT KILOMETROS_pk PRIMARY KEY  (TRAMOS_IdTramo,MUNICIPIOS_IdMunicipio)
);

-- Table: MUNICIPIOS
CREATE TABLE MUNICIPIOS (
    IdMunicipio int  NOT NULL IDENTITY,
    CONSTRAINT MUNICIPIOS_pk PRIMARY KEY  (IdMunicipio)
);

-- Table: TRAMOS
CREATE TABLE TRAMOS (
    IdTramo int  NOT NULL IDENTITY,
    AREAS_IdArea int  NOT NULL,
    CARRETERAS_IdCarretera int  NOT NULL,
    CONSTRAINT TRAMOS_pk PRIMARY KEY  (IdTramo)
);

-- foreign keys
-- Reference: KILOMETROS_MUNICIPIOS (table: KILOMETROS)
ALTER TABLE KILOMETROS ADD CONSTRAINT KILOMETROS_MUNICIPIOS
    FOREIGN KEY (MUNICIPIOS_IdMunicipio)
    REFERENCES MUNICIPIOS (IdMunicipio);

-- Reference: KILOMETROS_TRAMOS (table: KILOMETROS)
ALTER TABLE KILOMETROS ADD CONSTRAINT KILOMETROS_TRAMOS
    FOREIGN KEY (TRAMOS_IdTramo)
    REFERENCES TRAMOS (IdTramo);

-- Reference: TRAMOS_AREAS (table: TRAMOS)
ALTER TABLE TRAMOS ADD CONSTRAINT TRAMOS_AREAS
    FOREIGN KEY (AREAS_IdArea)
    REFERENCES AREAS (IdArea);

-- Reference: TRAMOS_CARRETERAS (table: TRAMOS)
ALTER TABLE TRAMOS ADD CONSTRAINT TRAMOS_CARRETERAS
    FOREIGN KEY (CARRETERAS_IdCarretera)
    REFERENCES CARRETERAS (IdCarretera);

-- End of file.

