CREATE TABLE Socios
(
  SocioID INT NOT NULL,
  Nombre VARCHAR(25) NOT NULL,
  Apellido VARCHAR(25) NOT NULL,
  DNI INT NOT NULL,
  Calle VARCHAR(50) NOT NULL,
  Numero INT NOT NULL,
  PRIMARY KEY (SocioID)
);

CREATE TABLE Editoriales
(
  EditorialID INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Calle VARCHAR(50) NOT NULL,
  Numero INT NOT NULL,
  PRIMARY KEY (EditorialID)
);

CREATE TABLE Proveedores
(
  ProveedorID INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Calle VARCHAR(50) NOT NULL,
  Numero INT NOT NULL,
  PRIMARY KEY (ProveedorID)
);

CREATE TABLE Bibliotecarios
(
  LegajoID INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (LegajoID)
);

CREATE TABLE Socio_Telefono
(
  Telefono VARCHAR(17) NOT NULL,
  SocioID INT NOT NULL,
  PRIMARY KEY (Telefono, SocioID),
  FOREIGN KEY (SocioID) REFERENCES Socios(SocioID)
);

CREATE TABLE Libros
(
  AñoEdicion INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  Título VARCHAR(50) NOT NULL,
  AñoEscritura INT NOT NULL,
  ProveedorID INT NOT NULL,
  LegajoID INT NOT NULL,
  PRIMARY KEY (ISBN),
  FOREIGN KEY (ProveedorID) REFERENCES Proveedores(ProveedorID),
  FOREIGN KEY (LegajoID) REFERENCES Bibliotecarios(LegajoID)
);

CREATE TABLE Ejemplares
(
  EjemplarID INT NOT NULL,
  Deteriorado INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (ISBN),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);

CREATE TABLE Prestamos
(
  FechaPrestamo DATE NOT NULL,
  FechaTope DATE NOT NULL,
  FechaDevolucion DATE NOT NULL,
  SocioId INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (SocioId, ISBN),
  FOREIGN KEY (SocioId) REFERENCES Socios(SocioID),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);

CREATE TABLE Libro_Editorial
(
  ISBN VARCHAR(17) NOT NULL,
  EditorialID INT NOT NULL,
  PRIMARY KEY (ISBN, EditorialID),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN),
  FOREIGN KEY (EditorialID) REFERENCES Editoriales(EditorialID)
);

CREATE TABLE Libro_Autor
(
  Autor VARCHAR(50) NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (Autor, ISBN),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);