@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Gerardo Tordoya

'========= 2022-09-01 =========

Alfa -> Beta: Mensaje enviado
Beta -> Gamma: Mensaje reenviado
Gamma --> Alfa: Mensaje recibido

caption https://www.planttext.com/

@enduml