@startuml Samples

    ' ================================= TWEAKS =================================
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false
    ' --------------------------------------------------------------------------

    title Diagrama

    Bob -> Alice: Hello!

@enduml