@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title https://www.planttext.com/
'====================================

Alfa -> Beta: Enviándote un mensaje

@enduml