/'
  @title        CAJERO BANCARIO
  @description  Ejercicio del banco con POO
  @author       Gerardo Tordoya
  @date         2022-10-13
  @remark       Para generar este archivo .puml se usó:
                *) pyreverse -ASmy -o puml ejercicio_banco_poo.py
                *) pyreverse -o puml ejercicio_banco_poo.py
  @credits      https://github.com/PyCQA/pylint/issues/5950
                https://pylint.pycqa.org/en/v2.15.3/pyreverse.html
'/

@startuml Cajero Bancario en POO

' Configuración de plantilla.
skin rose
skinparam classFontName Calibri
skinparam shadowing false
skinparam linetype ortho
'hide circle

' ──────────────────────────────────────────────────────────────────────────────
title Diagrama de clases generado por pyreverse
' ──────────────────────────────────────────────────────────────────────────────

set namespaceSeparator none

class "LinkedList" as ejercicio_banco_poo.LinkedList
{
    next
    value
    append(nodo)
    index(index)
    set_index(index, value)
    size()
}

ejercicio_banco_poo.LinkedList --* ejercicio_banco_poo.LinkedList : next

' ──────────────────────────────────────────────────────────────────────────────
caption pyreverse -o puml <archivo>.py
' ──────────────────────────────────────────────────────────────────────────────

@enduml
