@startuml MDS

' skin rose
' skinparam classFontName Calibri
' skinparam shadowing false
hide circle
skinparam linetype ortho

title Diagrama de Libro

class "Informe Preliminar de Investigación"

class Prototipos

class "Presupuesto y Programa"

class "Especificaciones de Requerimientos"

class "Casos de Uso"
{
    -Todos de alto nivel
    -Algunos esenciales expandidos
}

class "Diagramas de Casos de Uso"

class "Modelo Conceptual Preliminar"

class Glosario

"Informe Preliminar de Investigación" <-- "Especificaciones de Requerimientos"

Prototipos <-- "Especificaciones de Requerimientos"
Prototipos <-- "Casos de Uso"

"Presupuesto y Programa" --> "Especificaciones de Requerimientos"
"Presupuesto y Programa" --> "Casos de Uso"
"Presupuesto y Programa" --> "Modelo Conceptual Preliminar"

"Especificaciones de Requerimientos" <-- "Casos de Uso"
"Casos de Uso" <-- "Diagramas de Casos de Uso"

"Modelo Conceptual Preliminar" --> "Casos de Uso"
"Modelo Conceptual Preliminar" --> "Especificaciones de Requerimientos"

Glosario -> "Casos de Uso"
Glosario -> "Especificaciones de Requerimientos"


@enduml