' =======================================
' Author:      Gerardo Tordoya
' Create date: 2022-11-02
' Description: Arquitectura LUG (7 Capas)
' =======================================

@startuml Gestor de Campeonatos

' ─── CONFIGURACIONES ──────────────────────────────────────────────────────────

skin rose
skinparam classFontName Calibri
' skinparam shadowing false
' hide circle
skinparam linetype ortho

' --- TÍTULO ───────────────────────────────────────────────────────────────────

title Arquitectura UAI de 6 Capas

' ─── ENTIDADES ────────────────────────────────────────────────────────────────

package BEL
{
}

package UIL
{
}

package BLL
{
}

package MPP
{
}

package DAL
{
}

package ABS
{
}

package DAT <<Database>>
{
}

' ─── RELACIONES ───────────────────────────────────────────────────────────────

BLL -[plain]-> MPP
DAL -[plain]-> DAT
MPP -[plain]-> DAL
UIL -[plain]-> BLL

BLL -[plain]-> BEL
MPP -[plain]-> BEL
UIL -[plain]-> BEL

BEL -[plain]-> ABS
BLL -[plain]-> ABS
MPP -[plain]-> ABS

' ─── NOTAS ────────────────────────────────────────────────────────────────────


' ─── SUBTÍTULO ────────────────────────────────────────────────────────────────

caption Última actualización: 2022-11-04

' ─── FIN ──────────────────────────────────────────────────────────────────────
@enduml