' =======================================
' Author:      Gerardo Tordoya
' Create date: 2022-11-02
' Description: Arquitectura LUG (6 Capas)
' =======================================

@startuml Gestor de Campeonatos

' ─── CONFIGURACIONES ──────────────────────────────────────────────────────────
skin rose
' skinparam classFontName Calibri
' skinparam shadowing false
' hide circle
skinparam linetype ortho

' --- TÍTULO ───────────────────────────────────────────────────────────────────
title Arquitectura UAI de 6 Capas

' ─── ENTIDADES ────────────────────────────────────────────────────────────────
package BEL
{
}

package UIL
{
}

package BLL
{
}

package MPP
{
}

package DAL
{
}

package ABS
{
}

package SQL <<Database>>
{
}

' ─── RELACIONES ───────────────────────────────────────────────────────────────
UIL -[plain]-> BLL
BLL -[plain]-> MPP
MPP -[plain]-> DAL
DAL -[plain]-> SQL

UIL -[plain]-> BEL
BLL -[plain]-> BEL
MPP -[plain]-> BEL

BLL -[plain]-> ABS
MPP -[plain]-> ABS



' ─── NOTAS ────────────────────────────────────────────────────────────────────


' ─── SUBTÍTULO ────────────────────────────────────────────────────────────────
caption Última actualización: 2022-11-02

' ─── FIN ──────────────────────────────────────────────────────────────────────
@enduml