@startmindmap Gestor de Campeonatos


' ======================================================
' Author:      Gerardo Tordoya
' Create date: 2022-10-29
' Description: Propuesta para el Cuadro de Eliminatorias
' ======================================================


' ..............................................................................

title Propuesta para el Cuadro de Eliminatorias

' ─── DIAGRAMA ─────────────────────────────────────────────────────────────────

* Variables

left side

    ** <&flag>Cualitativas

        *** Nominales
            **** Nombre
            **** Marca
            **** Color
            **** Estado Civil

        *** Ordinales
            **** Nivel de escolaridad
            **** Grado militar
            **** Calificacion
            **** Etapa de desarrollo

right side

    ** Cuantitativas

        *** Discretas
        **** Cantidad de mascotas
        **** Edad (en años)
        **** Número de páginas

        *** Continuas
        **** Saldo bancario
        **** Tiempo
        **** Velocidad

' ──────────────────────────────────────────────────────────────────────────────

caption Mapa Mental

' ..............................................................................

@endmindmap