/'
  @title        GESTOR DE CAMPEONATOS
  @description  Aplicación para crear, organizar y administrar campeonatos.
  @author       Gerardo Tordoya
  @date         2022-10-12
'/

@startuml GESTOR DE CAMPEONATOS

' Configuración de plantilla.
skin rose
skinparam classFontName Calibri
skinparam shadowing false

' Configuración de diagrama.
hide circle
skinparam linetype ortho

' ──────────────────────────────────────────────────────────────────────────────

title Diseño de la Base de Datos SQL

' ─── OBJETOS ──────────────────────────────────────────────────────────────────

entity "Campeonato_Participantes"
{
    *Id:           int  <<generated>>
    --
    Campeonato_Id:  int  **<<FK>>**
    Equipo_Id:      int  **<<FK>>**
}


entity "Campeonato_Premios"
{
    *Id:           int  <<generated>>
    --
    Campeonato_Id:  int  **<<FK>>**
    Premio_Id:      int  **<<FK>>**
}


entity "Campeonatos"
{
    *Id:     int  <<generated>>
    --
    Nombre:  nvarchar(200)
    Tarifa:  money
}


entity "Equipo_Miembros"
{
    *Id:        int  <<generated>>
    --
    Equipo_Id:   int  **<<FK>>**
    Persona_Id:  int  **<<FK>>**
}


entity "Equipos"
{
    *Id:     int  <<generated>>
    --
    Nombre:  nvarchar(100)
}


entity "Partido_Participantes"
{
   *Id:                 int  <<generated>>
   --
    PartidoPresente_Id:  int  **<<FK>>**
    PartidoAnterior_Id:  int  **<<FK>>**
    Equipo_Id:           int  **<<FK>>**
    Puntaje:            int
}


entity "Partidos"
{
   *Id:         int  <<generated>>
   --
    Ganador_Id:  int  **<<FK>>**
    Ronda:      int
}


entity "Personas"
{
   *Id:        int  <<generated>>
   --
    Nombre:    nvarchar(100)
    Apellido:  nvarchar(100)
    Email:     nvarchar(100)
    Celular:   nvarchar(20)
}


entity "Premios"
{
    *Id:               int  <<generated>>
    --
    PuestoNumero:      int
    PuestoNombre:      nvarchar(50)
    PremioMonto:       money
    PremioPorcentaje:  float
}

' ─── RELACIONES ───────────────────────────────────────────────────────────────

Campeonatos ||--|{ Campeonato_Participantes
Campeonatos ||--|{ Campeonato_Premios

Equipos     ||--|{ Campeonato_Participantes
Equipos     ||--|{ Equipo_Miembros
Equipos     ||--|{ Partido_Participantes
Equipos     ||--|{ Partidos

Partidos    ||--|{ Partido_Participantes

Personas    ||--|{ Equipo_Miembros

Premios     ||--|{ Campeonato_Premios

' ──────────────────────────────────────────────────────────────────────────────

caption AUTOR \n **Gerardo Tordoya** \n 2022-10-12

' ──────────────────────────────────────────────────────────────────────────────

@enduml
