/'
  @title        GESTOR DE CAMPEONATOS
  @description  Aplicación para crear, organizar y administrar campeonatos.
  @author       Gerardo Tordoya
  @date         2022-10-12
'/

@startuml GESTOR DE CAMPEONATOS

' Configuración de plantilla.
skin rose
skinparam classFontName Calibri
skinparam shadowing false

' Configuración de diagrama.
hide circle
skinparam linetype ortho

' ──────────────────────────────────────────────────────────────────────────────

title Diseño de la Base de Datos SQL

' ─── OBJETOS ──────────────────────────────────────────────────────────────────

entity "CampeonatoParticipantes"
{
    *ID:           int  <<generated>>
    --
    CampeonatoID:  int  **<<FK>>**
    EquipoID:      int  **<<FK>>**
}


entity "CampeonatoPremios"
{
    *ID:           int  <<generated>>
    --
    CampeonatoID:  int  **<<FK>>**
    PremioID:      int  **<<FK>>**
}


entity "Campeonatos"
{
    *ID:     int  <<generated>>
    --
    Nombre:  nvarchar(200)
    Tarifa:  money
}


entity "EquipoMiembros"
{
    *ID:        int  <<generated>>
    --
    EquipoID:   int  **<<FK>>**
    PersonaID:  int  **<<FK>>**
}


entity "Equipos"
{
    *ID:     int  <<generated>>
    --
    Nombre:  nvarchar(100)
}


entity "PartidoParticipantes"
{
   *ID:                 int  <<generated>>
   --
    PartidoPresenteID:  int  **<<FK>>**
    PartidoAnteriorID:  int  **<<FK>>**
    EquipoID:           int  **<<FK>>**
    Puntaje:            int
}


entity "Partidos"
{
   *ID:         int  <<generated>>
   --
    GanadorID:  int  **<<FK>>**
    Ronda:      int
}


entity "Personas"
{
   *ID:        int  <<generated>>
   --
    Nombre:    nvarchar(100)
    Apellido:  nvarchar(100)
    Email:     nvarchar(100)
    Celular:   nvarchar(20)
}


entity "Premios"
{
    *ID:               int  <<generated>>
    --
    PuestoNumero:      int
    PuestoNombre:      nvarchar(50)
    PremioMonto:       money
    PremioPorcentaje:  float
}

' ─── RELACIONES ───────────────────────────────────────────────────────────────

Campeonatos ||--|{ CampeonatoParticipantes
Campeonatos ||--|{ CampeonatoPremios

Equipos     ||--|{ CampeonatoParticipantes
Equipos     ||--|{ EquipoMiembros
Equipos     ||--|{ PartidoParticipantes
Equipos     ||--|{ Partidos

Partidos    ||--|{ PartidoParticipantes

Personas    ||--|{ EquipoMiembros

Premios     ||--|{ CampeonatoPremios

' ──────────────────────────────────────────────────────────────────────────────

caption AUTOR \n **Gerardo Tordoya** \n 2022-10-12

' ──────────────────────────────────────────────────────────────────────────────

@enduml
